### ISSUE TITLE
Dragging a file on top of a different directory should move it by default

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#40] opened 2012-03-24 12:44 UTC
Instead of copying it (current behaviour)

**Comment by ABBAPOH** [comment] 2013-01-07 17:29
Seems to be fixed now. Reopen if still reproduces.

Current behavior - to move if destination is on the same drive or copy otherwise.

**Closed as completed by ABBAPOH** 2013-01-07 17:29 UTC
